import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const base=new URL('../',import.meta.url);
const read=path=>readFile(new URL(path,base),'utf8');
const ctx={window:{},console};
for(const file of ['website/data/catalogue.js','website/data/demo-data.js','website/data/planting-plan-rules.v0.1.js','website/planting-engine.js'])vm.runInNewContext(await read(file),ctx);
const {PlantscapesEngine:E,PLANTSCAPES_RULEBOOK:book}=ctx.window;
assert.equal(book.review_state,'design_policy_approved_species_validation_pending');
assert.equal(book.first_release_policy.sightline_drawing_required,false);
assert.ok(ctx.window.PLANTSCAPES_CATALOGUE.length>=2400);
const canonical=JSON.parse(await read('dataset/planting-plan-rules.v0.1.json'));
assert.equal(JSON.stringify(book),JSON.stringify(canonical),'browser must use the canonical approved rulebook');
const ruleIds=new Set(book.rules.map(r=>r.id));
const boundary=[[0,0],[28,0],[28,20],[0,20]];
const zone={id:1,name:'Park bed',conditions:{soil:'clay',moisture:'fresh',light:'sun',hydrology:'none',waterEdge:'no',source:'demo'}};
const p=(id,group,height,spread,extra={})=>E.enrich({id,name:id,latin:id,group,height,spread,demo:true,moisture:'fresh',light:'mixed',from:6,to:9,colour:'purple',caution:'verify',...extra});
const plants=[p('low','Flowers & herbs',.3,.45),p('middle','Flowers & herbs',.8,.65),p('tall','Grasses, sedges & rushes',1.8,.8),p('shrub','Shrubs',3,2.8),p('tree','Trees',10,6),p('ornamental','Flowers & herbs',.45,.5,{nativeStatus:'non_native_fixture'}),{id:'name-only',name:'Name only',group:'Flowers & herbs',reviewed:false}];
const project={type:'landscape',rewilding:false,character:'mosaic',publicAccess:true,maintenance:'moderate',priorities:['pollinators']};
const input={boundary,beds:[{polygon:boundary,zoneId:1}],paths:[[[14,0],[14,20]]],plants,project,zones:[zone],pathWidth:1.5};
assert.match(E.generate({...input,paths:[]}).error,/Draw and finish the paths/);
assert.match(E.generate({...input,plants:[plants.at(-1)]}).error,/No eligible plants/);
const result=E.generate(input);
assert.ok(result.placements.length>50,'a working park preview must contain plants');
assert.ok(result.placements.every(p=>result.valid(p.xy)),'placements must respect boundary and path');
assert.ok(result.placements.every(p=>p.ruleTrace.every(id=>ruleIds.has(id))),'every placement must trace to a real rule');
assert.ok(result.decisions.some(d=>d.plantId==='name-only'&&!d.eligible));
assert.ok(result.visibility.length>=2,'path endpoints must produce municipal review prompts');
for(const item of result.placements.filter(p=>result.pathDistance(p.xy)<E.config.edgeDepth))assert.ok(item.height<=E.config.edgeHeight,'low planting at the route edge');
assert.ok(result.placements.some(p=>p.height>1.3),'taller structure should be possible in the interior');
const rewild=E.generate({...input,project:{...project,rewilding:true}});
assert.ok(rewild.placements.every(p=>p.plantId!=='ornamental'));
assert.ok(rewild.decisions.some(d=>d.plantId==='ornamental'&&d.rules.includes('G05')));
assert.equal(E.eligibility(plants[5],{...project,type:'restoration'}).eligible,false);
assert.equal(E.eligibility(plants[5],{...project,type:'restoration',restorationOrnamentals:true}).eligible,true);
const dense=E.generate({...input,plants:[p('one','Flowers & herbs',.3,.4)]});
const sparse=E.generate({...input,plants:[p('one','Flowers & herbs',.3,.95)]});
assert.ok(dense.placements.length>sparse.placements.length*2,'mature spread must meaningfully change quantities');
const wider=E.generate({...input,plants:[p('one','Flowers & herbs',.3,.4)],pathWidth:5});
assert.ok(wider.placements.length<dense.placements.length,'wider paths must reduce plantable area');
const dry=p('dry','Flowers & herbs',.4,.5,{moisture:'dry',light:'sun'});
assert.equal(E.zoneFit(dry,{...zone,conditions:{...zone.conditions,moisture:'wet'}},project).fit,false);
const water=p('water','Aquatic & marginal plants',.4,.5,{moisture:'wet'});
assert.equal(E.zoneFit(water,zone,project).fit,false);
assert.equal(E.zoneFit(water,{...zone,conditions:{...zone.conditions,moisture:'wet',waterEdge:'yes',hydrology:'seasonal'}},project).fit,true);
assert.equal(E.zoneFit(dry,{...zone,conditions:{...zone.conditions,soil:'unknown'}},project).fit,false);
assert.equal(E.eligibility(p('climber','Climbers',3,1),project).eligible,false);
const wetZone={...zone,conditions:{...zone.conditions,moisture:'wet',waterEdge:'yes',hydrology:'permanent'}};
const waterPolygon=[[2,2],[10,2],[10,14],[2,14]];
const wetResult=E.generate({...input,zones:[wetZone],waterBeds:[{polygon:waterPolygon,zoneId:1}],plants:[plants[0],water]});
assert.ok(wetResult.placements.some(p=>p.plantId==='water'&&E.inside(p.xy,waterPolygon)),'marginals must appear on the water shoreline');
assert.ok(wetResult.placements.filter(p=>p.plantId==='water').every(p=>wetResult.shoreDistance(p.xy)<=1.2),'marginals must not fill deep water or ordinary land');
assert.ok(wetResult.placements.filter(p=>p.plantId!=='water').every(p=>!E.inside(p.xy,waterPolygon)),'terrestrial plants cannot be in water');
const noWater=E.generate({...input,zones:[wetZone],plants:[plants[0],water]});
assert.ok(noWater.placements.every(p=>p.plantId!=='water'),'aquatics must not be spread through an ordinary land bed');
vm.runInNewContext(await read('website/plan-graphics.js'),ctx);
const graphics=ctx.window.PlantscapesGraphics;
assert.equal(new Set(Array.from({length:9},(_,i)=>graphics.pattern(i+1,'#123456','test'))).size,9);
const view=graphics.elevated({boundary,sketches:[{type:'water',points:waterPolygon},{type:'open',points:[[20,2],[25,2],[25,6]]},{type:'path',points:[[14,0],[14,20]]}],placements:wetResult.placements,plants:[plants[0],water],masses:[],keys:[],direction:'south',season:'summer',age:5,angle:'elevated',pathWidth:1.5,colours:{}});
for(const surface of ['water','open','path'])assert.ok(view.svg.includes('data-surface="'+surface+'"'));
const html=await read('website/index.html');
for(const id of ['sketchZone','planNotation','mixMatrix','planRuleReview','undoPlanEdit'])assert.ok(html.includes('id="'+id+'"'));
for(const id of ['pathWidth','demoGenerate','addCenterShape'])assert.ok(!html.includes('id="'+id+'"'),'removed UI clutter: '+id);
assert.ok(html.indexOf('id="planNotation"')<html.indexOf('id="map"'),'legend must precede the map');
const repeated=E.generate(input);
assert.equal(JSON.stringify(result.placements),JSON.stringify(repeated.placements),'seeded intermingling must be reproducible');
const speciesPerCell=new Map();for(const item of result.placements.filter(p=>!p.tree)){const cell=Math.floor(item.xy[0]/2)+':'+Math.floor(item.xy[1]/2);if(!speciesPerCell.has(cell))speciesPerCell.set(cell,new Set());speciesPerCell.get(cell).add(item.plantId);}
assert.ok([...speciesPerCell.values()].filter(s=>s.size>1).length>10,'naturalistic planting must mix species within small cells');
const grassOnly=E.generate({...input,plants:[plants[0],plants[2]],mix:{matrix:100,flowers:0,structure:0}});
assert.ok(grassOnly.placements.filter(p=>grassOnly.pathDistance(p.xy)>E.config.transitionDepth).every(p=>p.plantId==='tall'),'available positive weights should select the requested role');
const app=await read('website/app.js');
new vm.Script(app);
assert.ok(!app.includes('{color,weight'),'rendering regression: undefined colour');
assert.ok(!app.includes('{renderer,radius'),'rendering regression: undefined renderer');
console.log('Passed: canonical rulebook, path-first generation, visible plants, mature spacing, edge heights, native policy, zone gates, name-only exclusion and municipal review prompts.');
